Repository axiomhq/axiom-go, pull requests merged in 2021-01, with the labels that each got.

#2 Improve documentation
  .github/workflows/go.yml
  README.md
  adapters/README.md
  axiom/client_integration_test.go
  go.mod
  go.sum
Labels: enhancement

#3 Fix gopkg badge
  README.md
Labels: documentation

#4 Fix license date `2021`
  README.md
Labels: documentation

#5 Rename caseInsensitive to caseSensitive
  axiom/monitors_test.go
  axiom/query/filter.go
Labels: bug
